#!/usr/bin/env python3
"""
ChargeGap Europe — data refresh (ETL)
=====================================

Replaces the indicative snapshot in data/countries.js|json with fresh pulls
from public sources, keeping the file format the web app expects.

Sources
-------
1. Eurostat API (no key needed) — automatic:
     • road_eqs_carpda  : battery-electric passenger-car stock (end of year)
     • demo_pjan        : population on 1 January
   NOTE ON CONVENTION: the model stores BEV stock at 1 January (KBA-style),
   so Eurostat's end-of-year value for year Y is written into panel year Y+1.
   UK left Eurostat reporting after 2019 and CH coverage is partial — those
   series keep their previous values and are flagged in `refresh_log`.

2. EAFO charging points — manual drop-in (no stable public API):
     Export the country CSVs from
     https://alternative-fuels-observatory.ec.europa.eu
     into  etl/manual/eafo_points.csv  with the columns
         country,year,ac_points,dc_points
     (country = ISO-2 code used in the panel, year = 1-Jan panel year).

3. Local overrides — etl/overrides/*.json, merged last. Each file is a
   partial country object keyed by "code", e.g. to set an official target:
     { "code": "FR", "fleet_2030_target": 15400000,
       "fleet_target_note": "…", "quality": "indicative" }

Usage
-----
    pip install -r etl/requirements.txt
    python etl/fetch_data.py                 # refresh everything possible
    python etl/fetch_data.py --offline       # re-emit files from current data
    python etl/fetch_data.py --countries DE,FR,NL

The script never invents values: anything it cannot refresh keeps the
previous number and the country's `quality` flag stays "indicative".
A country flips to "verified" only via an explicit override file.
"""
from __future__ import annotations
import argparse, csv, datetime as dt, json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA_JS = ROOT / "data" / "countries.js"
DATA_JSON = ROOT / "data" / "countries.json"
MANUAL_EAFO = ROOT / "etl" / "manual" / "eafo_points.csv"
OVERRIDES_DIR = ROOT / "etl" / "overrides"

EUROSTAT = "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/{ds}"
# Panel ISO-2 → Eurostat geo code (UK dropped out of reporting; kept for shape)
GEO = {"DE": "DE", "NO": "NO", "FR": "FR", "NL": "NL", "UK": "UK", "AT": "AT",
       "ES": "ES", "IT": "IT", "BE": "BE", "SE": "SE", "DK": "DK", "FI": "FI",
       "CH": "CH", "CZ": "CZ"}


# ── load / save the app data file ────────────────────────────────────────
def load_panel() -> dict:
    """countries.json is the canonical machine-readable copy."""
    return json.loads(DATA_JSON.read_text(encoding="utf-8"))


HEADER_COMMENT = """/* ============================================================================
 * ChargeGap Europe — country panel dataset (generated by etl/fetch_data.py)
 * Stock convention: BEV passenger-car stock at 1 January of each panel year.
 * quality: "verified" = source-verified series · "indicative" = estimate,
 * refresh before citing. See README → Data & honesty.
 * ========================================================================== */
"""


def save_panel(panel: dict) -> None:
    panel["generated"] = dt.date.today().isoformat()
    DATA_JSON.write_text(json.dumps(panel, indent=2, ensure_ascii=False) + "\n",
                         encoding="utf-8")
    DATA_JS.write_text(HEADER_COMMENT + "window.CG_DATA = " +
                       json.dumps(panel, indent=2, ensure_ascii=False) + ";\n",
                       encoding="utf-8")
    print(f"✓ wrote {DATA_JSON.relative_to(ROOT)} and {DATA_JS.relative_to(ROOT)}")


# ── Eurostat (JSON-stat 2.0) ─────────────────────────────────────────────
def eurostat_series(session, dataset: str, geo: str, extra: dict) -> dict[int, float]:
    """Return {year: value} for one geo from a Eurostat dataset."""
    params = {"format": "JSON", "lang": "EN", "geo": geo, **extra}
    r = session.get(EUROSTAT.format(ds=dataset), params=params, timeout=60)
    r.raise_for_status()
    js = r.json()
    time_idx = js["dimension"]["time"]["category"]["index"]
    out = {}
    for label, idx in time_idx.items():
        if str(idx) in js["value"] or idx in js["value"]:
            v = js["value"].get(str(idx), js["value"].get(idx))
            m = re.match(r"(\d{4})", label)
            if m and v is not None:
                out[int(m.group(1))] = float(v)
    return out


def refresh_eurostat(panel: dict, codes: list[str], log: dict) -> None:
    try:
        import requests
    except ImportError:
        sys.exit("requests missing — pip install -r etl/requirements.txt")
    s = requests.Session()
    s.headers["User-Agent"] = "chargegap-europe-etl (open-source, github.com/itsViru)"

    for c in panel["countries"]:
        if c["code"] not in codes:
            continue
        geo = GEO.get(c["code"])
        entry = log.setdefault(c["code"], [])
        # BEV stock — end-of-year Y feeds panel year Y+1 (1-Jan convention)
        try:
            bev = eurostat_series(s, "road_eqs_carpda", geo,
                                  {"mot_nrg": "ELC", "unit": "NR"})
            hits = 0
            for i, y in enumerate(c["years"]):
                if (y - 1) in bev:
                    c["bev_stock"][i] = int(round(bev[y - 1]))
                    hits += 1
            entry.append(f"bev_stock: {hits}/{len(c['years'])} years from Eurostat")
        except Exception as e:  # keep old values, record why
            entry.append(f"bev_stock: kept snapshot ({type(e).__name__}: {e})")
        # population (millions, latest available)
        try:
            pop = eurostat_series(s, "demo_pjan", geo,
                                  {"sex": "T", "age": "TOTAL", "unit": "NR"})
            if pop:
                latest = max(pop)
                c["population_m"] = round(pop[latest] / 1e6, 2)
                entry.append(f"population_m: {c['population_m']} ({latest})")
        except Exception as e:
            entry.append(f"population_m: kept snapshot ({type(e).__name__})")


# ── EAFO manual drop-in ──────────────────────────────────────────────────
def merge_eafo_csv(panel: dict, log: dict) -> None:
    if not MANUAL_EAFO.exists():
        print(f"· no {MANUAL_EAFO.relative_to(ROOT)} — charging points unchanged "
              "(export from EAFO to refresh; see file docstring)")
        return
    rows = list(csv.DictReader(MANUAL_EAFO.open(encoding="utf-8")))
    by_c: dict[str, list[dict]] = {}
    for r in rows:
        by_c.setdefault(r["country"].strip().upper(), []).append(r)
    for c in panel["countries"]:
        for r in by_c.get(c["code"], []):
            y = int(r["year"])
            if y in c["years"]:
                i = c["years"].index(y)
                if r.get("ac_points"):
                    c["ac_points"][i] = int(float(r["ac_points"]))
                if r.get("dc_points"):
                    c["dc_points"][i] = int(float(r["dc_points"]))
        if c["code"] in by_c:
            log.setdefault(c["code"], []).append(
                f"charging points: {len(by_c[c['code']])} rows from EAFO CSV")


# ── overrides ────────────────────────────────────────────────────────────
def merge_overrides(panel: dict, log: dict) -> None:
    if not OVERRIDES_DIR.exists():
        return
    for f in sorted(OVERRIDES_DIR.glob("*.json")):
        o = json.loads(f.read_text(encoding="utf-8"))
        for c in panel["countries"]:
            if c["code"] == o.get("code"):
                c.update({k: v for k, v in o.items() if k != "code"})
                log.setdefault(c["code"], []).append(f"override applied: {f.name}")


# ── main ─────────────────────────────────────────────────────────────────
def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--offline", action="store_true",
                    help="skip Eurostat; only re-emit files (+ CSV/overrides)")
    ap.add_argument("--countries", default=",".join(GEO),
                    help="comma-separated ISO-2 codes to refresh")
    args = ap.parse_args()
    codes = [c.strip().upper() for c in args.countries.split(",") if c.strip()]

    panel = load_panel()
    log: dict[str, list[str]] = {}
    if not args.offline:
        refresh_eurostat(panel, codes, log)
    merge_eafo_csv(panel, log)
    merge_overrides(panel, log)
    panel["refresh_log"] = {"date": dt.date.today().isoformat(), "detail": log}
    panel["snapshot_note"] = ("Refreshed via etl/fetch_data.py where sources allow; "
                              "series without a fresh pull keep snapshot values — "
                              "see refresh_log and per-country quality flags.")
    save_panel(panel)
    for code, lines in log.items():
        print(f"  {code}: " + " · ".join(lines))


if __name__ == "__main__":
    main()
