#!/usr/bin/env python3
"""
ChargeGap Europe — geo build step (dev-time only, NOT needed at runtime).

Compiles two open GeoJSON sources into data/geo.js (window.CG_GEO): compact
SVG path strings for (a) the 14 panel countries and (b) the 16 German
Bundesländer. Runtime stays dependency-free (inline SVG, works on file://).

Sources & licences (attribution shipped in Model Audit):
  * Natural Earth 1:50m admin-0 countries — public domain
    https://github.com/nvkelso/natural-earth-vector
  * deutschlandGeoJSON (isellsoap), based on © GeoBasis-DE / BKG 2022,
    Licence dl-de/by-2-0 — https://github.com/isellsoap/deutschlandGeoJSON

Usage:  pip install shapely && python3 tools/build_geo.py
"""
import json, math, os
from shapely.geometry import shape, box
from shapely.ops import unary_union

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "geo_src")
OUT = os.path.join(HERE, "..", "data", "geo.js")

CODES = ["DE","NO","FR","NL","GB","AT","ES","IT","BE","SE","DK","FI","CH","CZ"]
ALIAS = {"GB": "UK"}   # panel keys Britain as UK; Natural Earth as GB
EU_BBOX = box(-11.5, 35.0, 32.0, 71.5)      # drops Svalbard + FR overseas
COSLAT = math.cos(math.radians(54.0))        # cos-corrected equirectangular

def rings(geom, min_area):
    """Yield exterior rings of polygon parts above the area threshold
    (largest part always kept, so no country vanishes)."""
    parts = list(geom.geoms) if geom.geom_type == "MultiPolygon" else [geom]
    parts.sort(key=lambda p: p.area, reverse=True)
    for i, p in enumerate(parts):
        if i == 0 or p.area >= min_area:
            yield list(p.exterior.coords)

def project(shapes, width, pad=8.0):
    """Fit all shapes into a shared viewBox; returns (paths, viewBox)."""
    pts = [(x * COSLAT, -y) for coords in shapes.values() for ring in coords for x, y in ring]
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    x0, y0 = min(xs), min(ys)
    s = (width - 2 * pad) / (max(xs) - x0)
    height = round((max(ys) - y0) * s + 2 * pad, 1)
    paths = {}
    for code, coords in shapes.items():
        d = []
        for ring in coords:
            pp = [(round((x * COSLAT - x0) * s + pad, 1),
                   round((-y - y0) * s + pad, 1)) for x, y in ring]
            d.append("M" + " ".join(f"{x} {y}" for x, y in pp) + "Z")
        paths[code] = "".join(d)
    return paths, f"0 0 {width} {height}"

def build_eu():
    ne = json.load(open(os.path.join(SRC, "ne_countries.geojson")))
    shapes = {}
    for f in ne["features"]:
        p = f["properties"]
        code = p.get("ISO_A2_EH") or p.get("ISO_A2")
        if code not in CODES:
            continue
        g = shape(f["geometry"]).intersection(EU_BBOX).simplify(0.07, True)
        if g.is_empty:
            raise SystemExit(f"{code}: empty after clip")
        shapes[ALIAS.get(code, code)] = list(rings(g, 0.12))
    want = sorted(ALIAS.get(c, c) for c in CODES)
    assert sorted(shapes) == want, f"missing: {set(want)-set(shapes)}"
    return project(shapes, 720)

def build_de():
    de = json.load(open(os.path.join(SRC, "de_laender.geojson")))
    shapes, names = {}, {}
    for f in de["features"]:
        code = f["properties"]["id"].replace("DE-", "")
        names[code] = f["properties"]["name"]
        g = shape(f["geometry"]).simplify(0.015, True)
        shapes[code] = list(rings(g, 0.005))
    assert len(shapes) == 16, len(shapes)
    paths, vb = project(shapes, 520)
    return paths, vb, names

eu_paths, eu_vb = build_eu()
de_paths, de_vb, de_names = build_de()

js = (
    "/* Generated by tools/build_geo.py — do not edit by hand.\n"
    " * Geometry: Natural Earth 1:50m (public domain) · Bundesländer via\n"
    " * isellsoap/deutschlandGeoJSON, © GeoBasis-DE / BKG 2022 (dl-de/by-2-0).\n"
    " * Stylised cos-corrected projection for choropleth use — not for navigation. */\n"
    "window.CG_GEO = " + json.dumps({
        "eu": {"viewBox": eu_vb, "shapes": eu_paths},
        "de": {"viewBox": de_vb, "shapes": de_paths, "names": de_names},
    }, separators=(",", ":")) + ";\n"
)
open(OUT, "w").write(js)
print(f"data/geo.js written: {os.path.getsize(OUT)/1024:.1f} KB · "
      f"EU shapes {len(eu_paths)} (vb {eu_vb}) · DE shapes {len(de_paths)} (vb {de_vb})")
